// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video_bank_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	pmongo "github.com/amsokol/mongo-go-driver-protobuf/pmongo"
	_ "github.com/amsokol/protoc-gen-gotag/tagger"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MV_ContentTypeOpt int32

const (
	MV_ContentTypeOpt_FREE    MV_ContentTypeOpt = 0
	MV_ContentTypeOpt_PREMIUM MV_ContentTypeOpt = 1
)

var MV_ContentTypeOpt_name = map[int32]string{
	0: "FREE",
	1: "PREMIUM",
}

var MV_ContentTypeOpt_value = map[string]int32{
	"FREE":    0,
	"PREMIUM": 1,
}

func (x MV_ContentTypeOpt) String() string {
	return proto.EnumName(MV_ContentTypeOpt_name, int32(x))
}

func (MV_ContentTypeOpt) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{0}
}

type MV_VideoTypeOpt int32

const (
	MV_VideoTypeOpt_GEN_MV        MV_VideoTypeOpt = 0
	MV_VideoTypeOpt_MUSIC_MV      MV_VideoTypeOpt = 1
	MV_VideoTypeOpt_ANIME_MV      MV_VideoTypeOpt = 2
	MV_VideoTypeOpt_ENGLISH_MV    MV_VideoTypeOpt = 3
	MV_VideoTypeOpt_GERMAN_MV     MV_VideoTypeOpt = 4
	MV_VideoTypeOpt_DUTCH_MV      MV_VideoTypeOpt = 5
	MV_VideoTypeOpt_FRENCH_MV     MV_VideoTypeOpt = 6
	MV_VideoTypeOpt_PUNJABI_MV    MV_VideoTypeOpt = 7
	MV_VideoTypeOpt_TAJIK_MV      MV_VideoTypeOpt = 8
	MV_VideoTypeOpt_INDONESIAN_MV MV_VideoTypeOpt = 9
	MV_VideoTypeOpt_HINDI_MV      MV_VideoTypeOpt = 11
	MV_VideoTypeOpt_TAGALOG_MV    MV_VideoTypeOpt = 12
	MV_VideoTypeOpt_HEBREW_MV     MV_VideoTypeOpt = 13
	MV_VideoTypeOpt_THAI_MV       MV_VideoTypeOpt = 14
	MV_VideoTypeOpt_GUJARATI_MV   MV_VideoTypeOpt = 15
	MV_VideoTypeOpt_JAPANESE_MV   MV_VideoTypeOpt = 16
	MV_VideoTypeOpt_KOREAN_MV     MV_VideoTypeOpt = 17
	MV_VideoTypeOpt_CHINESE_MV    MV_VideoTypeOpt = 18
	MV_VideoTypeOpt_MOROCCO_MV    MV_VideoTypeOpt = 19
	MV_VideoTypeOpt_SPANISH_MV    MV_VideoTypeOpt = 20
	MV_VideoTypeOpt_ASSAMESE_MV   MV_VideoTypeOpt = 21
)

var MV_VideoTypeOpt_name = map[int32]string{
	0:  "GEN_MV",
	1:  "MUSIC_MV",
	2:  "ANIME_MV",
	3:  "ENGLISH_MV",
	4:  "GERMAN_MV",
	5:  "DUTCH_MV",
	6:  "FRENCH_MV",
	7:  "PUNJABI_MV",
	8:  "TAJIK_MV",
	9:  "INDONESIAN_MV",
	11: "HINDI_MV",
	12: "TAGALOG_MV",
	13: "HEBREW_MV",
	14: "THAI_MV",
	15: "GUJARATI_MV",
	16: "JAPANESE_MV",
	17: "KOREAN_MV",
	18: "CHINESE_MV",
	19: "MOROCCO_MV",
	20: "SPANISH_MV",
	21: "ASSAMESE_MV",
}

var MV_VideoTypeOpt_value = map[string]int32{
	"GEN_MV":        0,
	"MUSIC_MV":      1,
	"ANIME_MV":      2,
	"ENGLISH_MV":    3,
	"GERMAN_MV":     4,
	"DUTCH_MV":      5,
	"FRENCH_MV":     6,
	"PUNJABI_MV":    7,
	"TAJIK_MV":      8,
	"INDONESIAN_MV": 9,
	"HINDI_MV":      11,
	"TAGALOG_MV":    12,
	"HEBREW_MV":     13,
	"THAI_MV":       14,
	"GUJARATI_MV":   15,
	"JAPANESE_MV":   16,
	"KOREAN_MV":     17,
	"CHINESE_MV":    18,
	"MOROCCO_MV":    19,
	"SPANISH_MV":    20,
	"ASSAMESE_MV":   21,
}

func (x MV_VideoTypeOpt) String() string {
	return proto.EnumName(MV_VideoTypeOpt_name, int32(x))
}

func (MV_VideoTypeOpt) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{1}
}

type MV_GenreOpt int32

const (
	MV_GenreOpt_ACTION               MV_GenreOpt = 0
	MV_GenreOpt_COMEDY               MV_GenreOpt = 1
	MV_GenreOpt_ROMANCE              MV_GenreOpt = 2
	MV_GenreOpt_THRILLER             MV_GenreOpt = 3
	MV_GenreOpt_HORROR               MV_GenreOpt = 4
	MV_GenreOpt_HISTORY              MV_GenreOpt = 5
	MV_GenreOpt_KOREAN               MV_GenreOpt = 6
	MV_GenreOpt_DRAMA                MV_GenreOpt = 7
	MV_GenreOpt_FANTASY              MV_GenreOpt = 8
	MV_GenreOpt_SCI_FI               MV_GenreOpt = 9
	MV_GenreOpt_ANIME                MV_GenreOpt = 10
	MV_GenreOpt_CRIME                MV_GenreOpt = 11
	MV_GenreOpt_SCI_FI_FANTASY       MV_GenreOpt = 12
	MV_GenreOpt_ACTION_ADVENTURE     MV_GenreOpt = 13
	MV_GenreOpt_FICTION              MV_GenreOpt = 14
	MV_GenreOpt_SPIRITUAL            MV_GenreOpt = 15
	MV_GenreOpt_RELIGION             MV_GenreOpt = 16
	MV_GenreOpt_TRAVEL               MV_GenreOpt = 17
	MV_GenreOpt_STYLE                MV_GenreOpt = 18
	MV_GenreOpt_CLASSIC              MV_GenreOpt = 19
	MV_GenreOpt_KIDS_FAMILY          MV_GenreOpt = 20
	MV_GenreOpt_MYSTERY              MV_GenreOpt = 21
	MV_GenreOpt_MUSICAL              MV_GenreOpt = 22
	MV_GenreOpt_SUPERHERO            MV_GenreOpt = 23
	MV_GenreOpt_POLITICS             MV_GenreOpt = 24
	MV_GenreOpt_MARTIAL_ARTS         MV_GenreOpt = 25
	MV_GenreOpt_SPORTS               MV_GenreOpt = 26
	MV_GenreOpt_KIDS                 MV_GenreOpt = 27
	MV_GenreOpt_ROMANTIC_THRILLERS   MV_GenreOpt = 28
	MV_GenreOpt_WAR                  MV_GenreOpt = 29
	MV_GenreOpt_FAMILY               MV_GenreOpt = 30
	MV_GenreOpt_HOLLYWOOD            MV_GenreOpt = 31
	MV_GenreOpt_CRITICALLY_ACCLAIMED MV_GenreOpt = 32
	MV_GenreOpt_DOCUMENTARY          MV_GenreOpt = 33
	MV_GenreOpt_OTHERS               MV_GenreOpt = 99
)

var MV_GenreOpt_name = map[int32]string{
	0:  "ACTION",
	1:  "COMEDY",
	2:  "ROMANCE",
	3:  "THRILLER",
	4:  "HORROR",
	5:  "HISTORY",
	6:  "KOREAN",
	7:  "DRAMA",
	8:  "FANTASY",
	9:  "SCI_FI",
	10: "ANIME",
	11: "CRIME",
	12: "SCI_FI_FANTASY",
	13: "ACTION_ADVENTURE",
	14: "FICTION",
	15: "SPIRITUAL",
	16: "RELIGION",
	17: "TRAVEL",
	18: "STYLE",
	19: "CLASSIC",
	20: "KIDS_FAMILY",
	21: "MYSTERY",
	22: "MUSICAL",
	23: "SUPERHERO",
	24: "POLITICS",
	25: "MARTIAL_ARTS",
	26: "SPORTS",
	27: "KIDS",
	28: "ROMANTIC_THRILLERS",
	29: "WAR",
	30: "FAMILY",
	31: "HOLLYWOOD",
	32: "CRITICALLY_ACCLAIMED",
	33: "DOCUMENTARY",
	99: "OTHERS",
}

var MV_GenreOpt_value = map[string]int32{
	"ACTION":               0,
	"COMEDY":               1,
	"ROMANCE":              2,
	"THRILLER":             3,
	"HORROR":               4,
	"HISTORY":              5,
	"KOREAN":               6,
	"DRAMA":                7,
	"FANTASY":              8,
	"SCI_FI":               9,
	"ANIME":                10,
	"CRIME":                11,
	"SCI_FI_FANTASY":       12,
	"ACTION_ADVENTURE":     13,
	"FICTION":              14,
	"SPIRITUAL":            15,
	"RELIGION":             16,
	"TRAVEL":               17,
	"STYLE":                18,
	"CLASSIC":              19,
	"KIDS_FAMILY":          20,
	"MYSTERY":              21,
	"MUSICAL":              22,
	"SUPERHERO":            23,
	"POLITICS":             24,
	"MARTIAL_ARTS":         25,
	"SPORTS":               26,
	"KIDS":                 27,
	"ROMANTIC_THRILLERS":   28,
	"WAR":                  29,
	"FAMILY":               30,
	"HOLLYWOOD":            31,
	"CRITICALLY_ACCLAIMED": 32,
	"DOCUMENTARY":          33,
	"OTHERS":               99,
}

func (x MV_GenreOpt) String() string {
	return proto.EnumName(MV_GenreOpt_name, int32(x))
}

func (MV_GenreOpt) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{2}
}

type VideoBank struct {
	Id            *pmongo.ObjectId `protobuf:"bytes,999,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	ContentId     string           `protobuf:"bytes,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Idx           string           `protobuf:"bytes,2,opt,name=idx,proto3" json:"idx,omitempty"`
	Provider      string           `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderShort string           `protobuf:"bytes,4,opt,name=providerShort,proto3" json:"providerShort,omitempty"`
	ProviderLabel string           `protobuf:"bytes,5,opt,name=providerLabel,proto3" json:"providerLabel,omitempty"`
	Title         string           `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// string titlePackage = 7;
	Tags                 []string             `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	VideoType            MV_VideoTypeOpt      `protobuf:"varint,9,opt,name=videoType,proto3,enum=v1.MV_VideoTypeOpt" json:"videoType,omitempty"`
	Genre                []MV_GenreOpt        `protobuf:"varint,10,rep,packed,name=genre,proto3,enum=v1.MV_GenreOpt" json:"genre,omitempty"`
	Year                 int32                `protobuf:"varint,11,opt,name=year,proto3" json:"year,omitempty"`
	Duration             string               `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	Synopsis             string               `protobuf:"bytes,14,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Cast                 []string             `protobuf:"bytes,15,rep,name=cast,proto3" json:"cast,omitempty"`
	PlayerUrl            string               `protobuf:"bytes,16,opt,name=playerUrl,proto3" json:"playerUrl,omitempty"`
	Poster               *MV_PosterData       `protobuf:"bytes,17,opt,name=poster,proto3" json:"poster,omitempty"`
	Director             []string             `protobuf:"bytes,18,rep,name=director,proto3" json:"director,omitempty"`
	ContentType          MV_ContentTypeOpt    `protobuf:"varint,19,opt,name=contentType,proto3,enum=v1.MV_ContentTypeOpt" json:"contentType,omitempty"`
	Availability         string               `protobuf:"bytes,20,opt,name=availability,proto3" json:"availability,omitempty"`
	ContentAs            string               `protobuf:"bytes,21,opt,name=contentAs,proto3" json:"contentAs,omitempty"`
	ContentLevel         int32                `protobuf:"varint,22,opt,name=contentLevel,proto3" json:"contentLevel,omitempty"`
	IsActive             bool                 `protobuf:"varint,23,opt,name=isActive,proto3" json:"isActive,omitempty"`
	IsValid              bool                 `protobuf:"varint,24,opt,name=isValid,proto3" json:"isValid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,25,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiredDate          *timestamp.Timestamp `protobuf:"bytes,33,opt,name=expiredDate,proto3" json:"expiredDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *VideoBank) Reset()         { *m = VideoBank{} }
func (m *VideoBank) String() string { return proto.CompactTextString(m) }
func (*VideoBank) ProtoMessage()    {}
func (*VideoBank) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{0}
}

func (m *VideoBank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoBank.Unmarshal(m, b)
}
func (m *VideoBank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoBank.Marshal(b, m, deterministic)
}
func (m *VideoBank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoBank.Merge(m, src)
}
func (m *VideoBank) XXX_Size() int {
	return xxx_messageInfo_VideoBank.Size(m)
}
func (m *VideoBank) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoBank.DiscardUnknown(m)
}

var xxx_messageInfo_VideoBank proto.InternalMessageInfo

func (m *VideoBank) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *VideoBank) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *VideoBank) GetIdx() string {
	if m != nil {
		return m.Idx
	}
	return ""
}

func (m *VideoBank) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *VideoBank) GetProviderShort() string {
	if m != nil {
		return m.ProviderShort
	}
	return ""
}

func (m *VideoBank) GetProviderLabel() string {
	if m != nil {
		return m.ProviderLabel
	}
	return ""
}

func (m *VideoBank) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoBank) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VideoBank) GetVideoType() MV_VideoTypeOpt {
	if m != nil {
		return m.VideoType
	}
	return MV_VideoTypeOpt_GEN_MV
}

func (m *VideoBank) GetGenre() []MV_GenreOpt {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *VideoBank) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *VideoBank) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *VideoBank) GetSynopsis() string {
	if m != nil {
		return m.Synopsis
	}
	return ""
}

func (m *VideoBank) GetCast() []string {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *VideoBank) GetPlayerUrl() string {
	if m != nil {
		return m.PlayerUrl
	}
	return ""
}

func (m *VideoBank) GetPoster() *MV_PosterData {
	if m != nil {
		return m.Poster
	}
	return nil
}

func (m *VideoBank) GetDirector() []string {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *VideoBank) GetContentType() MV_ContentTypeOpt {
	if m != nil {
		return m.ContentType
	}
	return MV_ContentTypeOpt_FREE
}

func (m *VideoBank) GetAvailability() string {
	if m != nil {
		return m.Availability
	}
	return ""
}

func (m *VideoBank) GetContentAs() string {
	if m != nil {
		return m.ContentAs
	}
	return ""
}

func (m *VideoBank) GetContentLevel() int32 {
	if m != nil {
		return m.ContentLevel
	}
	return 0
}

func (m *VideoBank) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *VideoBank) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VideoBank) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VideoBank) GetExpiredDate() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiredDate
	}
	return nil
}

type MV_PosterData struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	M                    string   `protobuf:"bytes,2,opt,name=m,proto3" json:"m,omitempty"`
	L                    string   `protobuf:"bytes,3,opt,name=l,proto3" json:"l,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_PosterData) Reset()         { *m = MV_PosterData{} }
func (m *MV_PosterData) String() string { return proto.CompactTextString(m) }
func (*MV_PosterData) ProtoMessage()    {}
func (*MV_PosterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{1}
}

func (m *MV_PosterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_PosterData.Unmarshal(m, b)
}
func (m *MV_PosterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_PosterData.Marshal(b, m, deterministic)
}
func (m *MV_PosterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_PosterData.Merge(m, src)
}
func (m *MV_PosterData) XXX_Size() int {
	return xxx_messageInfo_MV_PosterData.Size(m)
}
func (m *MV_PosterData) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_PosterData.DiscardUnknown(m)
}

var xxx_messageInfo_MV_PosterData proto.InternalMessageInfo

func (m *MV_PosterData) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *MV_PosterData) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

func (m *MV_PosterData) GetL() string {
	if m != nil {
		return m.L
	}
	return ""
}

type MV_CreateRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	VideoBank            *VideoBank `protobuf:"bytes,2,opt,name=videoBank,proto3" json:"videoBank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MV_CreateRequest) Reset()         { *m = MV_CreateRequest{} }
func (m *MV_CreateRequest) String() string { return proto.CompactTextString(m) }
func (*MV_CreateRequest) ProtoMessage()    {}
func (*MV_CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{2}
}

func (m *MV_CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_CreateRequest.Unmarshal(m, b)
}
func (m *MV_CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_CreateRequest.Marshal(b, m, deterministic)
}
func (m *MV_CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_CreateRequest.Merge(m, src)
}
func (m *MV_CreateRequest) XXX_Size() int {
	return xxx_messageInfo_MV_CreateRequest.Size(m)
}
func (m *MV_CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_CreateRequest proto.InternalMessageInfo

func (m *MV_CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_CreateRequest) GetVideoBank() *VideoBank {
	if m != nil {
		return m.VideoBank
	}
	return nil
}

type MV_CreateResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// string id = 2;
	// pmongo.ObjectId id = 2;
	Id                   *pmongo.ObjectId `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MV_CreateResponse) Reset()         { *m = MV_CreateResponse{} }
func (m *MV_CreateResponse) String() string { return proto.CompactTextString(m) }
func (*MV_CreateResponse) ProtoMessage()    {}
func (*MV_CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{3}
}

func (m *MV_CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_CreateResponse.Unmarshal(m, b)
}
func (m *MV_CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_CreateResponse.Marshal(b, m, deterministic)
}
func (m *MV_CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_CreateResponse.Merge(m, src)
}
func (m *MV_CreateResponse) XXX_Size() int {
	return xxx_messageInfo_MV_CreateResponse.Size(m)
}
func (m *MV_CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_CreateResponse proto.InternalMessageInfo

func (m *MV_CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_CreateResponse) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

type MV_CreateBulkRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// int32 bulkLimit
	VideoBankList        []*VideoBank `protobuf:"bytes,2,rep,name=videoBankList,proto3" json:"videoBankList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MV_CreateBulkRequest) Reset()         { *m = MV_CreateBulkRequest{} }
func (m *MV_CreateBulkRequest) String() string { return proto.CompactTextString(m) }
func (*MV_CreateBulkRequest) ProtoMessage()    {}
func (*MV_CreateBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{4}
}

func (m *MV_CreateBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_CreateBulkRequest.Unmarshal(m, b)
}
func (m *MV_CreateBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_CreateBulkRequest.Marshal(b, m, deterministic)
}
func (m *MV_CreateBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_CreateBulkRequest.Merge(m, src)
}
func (m *MV_CreateBulkRequest) XXX_Size() int {
	return xxx_messageInfo_MV_CreateBulkRequest.Size(m)
}
func (m *MV_CreateBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_CreateBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_CreateBulkRequest proto.InternalMessageInfo

func (m *MV_CreateBulkRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_CreateBulkRequest) GetVideoBankList() []*VideoBank {
	if m != nil {
		return m.VideoBankList
	}
	return nil
}

type MV_CreateBulkResponse struct {
	Api                  string             `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Ids                  []*pmongo.ObjectId `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MV_CreateBulkResponse) Reset()         { *m = MV_CreateBulkResponse{} }
func (m *MV_CreateBulkResponse) String() string { return proto.CompactTextString(m) }
func (*MV_CreateBulkResponse) ProtoMessage()    {}
func (*MV_CreateBulkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{5}
}

func (m *MV_CreateBulkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_CreateBulkResponse.Unmarshal(m, b)
}
func (m *MV_CreateBulkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_CreateBulkResponse.Marshal(b, m, deterministic)
}
func (m *MV_CreateBulkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_CreateBulkResponse.Merge(m, src)
}
func (m *MV_CreateBulkResponse) XXX_Size() int {
	return xxx_messageInfo_MV_CreateBulkResponse.Size(m)
}
func (m *MV_CreateBulkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_CreateBulkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_CreateBulkResponse proto.InternalMessageInfo

func (m *MV_CreateBulkResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_CreateBulkResponse) GetIds() []*pmongo.ObjectId {
	if m != nil {
		return m.Ids
	}
	return nil
}

type MV_ReadRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Idx                  string   `protobuf:"bytes,3,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_ReadRequest) Reset()         { *m = MV_ReadRequest{} }
func (m *MV_ReadRequest) String() string { return proto.CompactTextString(m) }
func (*MV_ReadRequest) ProtoMessage()    {}
func (*MV_ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{6}
}

func (m *MV_ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_ReadRequest.Unmarshal(m, b)
}
func (m *MV_ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_ReadRequest.Marshal(b, m, deterministic)
}
func (m *MV_ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_ReadRequest.Merge(m, src)
}
func (m *MV_ReadRequest) XXX_Size() int {
	return xxx_messageInfo_MV_ReadRequest.Size(m)
}
func (m *MV_ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_ReadRequest proto.InternalMessageInfo

func (m *MV_ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MV_ReadRequest) GetIdx() string {
	if m != nil {
		return m.Idx
	}
	return ""
}

type MV_ReadResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	VideoBank            *VideoBank `protobuf:"bytes,2,opt,name=videoBank,proto3" json:"videoBank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MV_ReadResponse) Reset()         { *m = MV_ReadResponse{} }
func (m *MV_ReadResponse) String() string { return proto.CompactTextString(m) }
func (*MV_ReadResponse) ProtoMessage()    {}
func (*MV_ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{7}
}

func (m *MV_ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_ReadResponse.Unmarshal(m, b)
}
func (m *MV_ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_ReadResponse.Marshal(b, m, deterministic)
}
func (m *MV_ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_ReadResponse.Merge(m, src)
}
func (m *MV_ReadResponse) XXX_Size() int {
	return xxx_messageInfo_MV_ReadResponse.Size(m)
}
func (m *MV_ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_ReadResponse proto.InternalMessageInfo

func (m *MV_ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_ReadResponse) GetVideoBank() *VideoBank {
	if m != nil {
		return m.VideoBank
	}
	return nil
}

type MV_UpdateRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	VideoBank            *VideoBank `protobuf:"bytes,2,opt,name=videoBank,proto3" json:"videoBank,omitempty"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MV_UpdateRequest) Reset()         { *m = MV_UpdateRequest{} }
func (m *MV_UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MV_UpdateRequest) ProtoMessage()    {}
func (*MV_UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{8}
}

func (m *MV_UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_UpdateRequest.Unmarshal(m, b)
}
func (m *MV_UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *MV_UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_UpdateRequest.Merge(m, src)
}
func (m *MV_UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MV_UpdateRequest.Size(m)
}
func (m *MV_UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_UpdateRequest proto.InternalMessageInfo

func (m *MV_UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_UpdateRequest) GetVideoBank() *VideoBank {
	if m != nil {
		return m.VideoBank
	}
	return nil
}

func (m *MV_UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MV_UpdateResponse struct {
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UpId                 *pmongo.ObjectId `protobuf:"bytes,2,opt,name=upId,proto3" json:"upId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MV_UpdateResponse) Reset()         { *m = MV_UpdateResponse{} }
func (m *MV_UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MV_UpdateResponse) ProtoMessage()    {}
func (*MV_UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{9}
}

func (m *MV_UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_UpdateResponse.Unmarshal(m, b)
}
func (m *MV_UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *MV_UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_UpdateResponse.Merge(m, src)
}
func (m *MV_UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MV_UpdateResponse.Size(m)
}
func (m *MV_UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_UpdateResponse proto.InternalMessageInfo

func (m *MV_UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_UpdateResponse) GetUpId() *pmongo.ObjectId {
	if m != nil {
		return m.UpId
	}
	return nil
}

type MV_DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,3,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_DeleteRequest) Reset()         { *m = MV_DeleteRequest{} }
func (m *MV_DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*MV_DeleteRequest) ProtoMessage()    {}
func (*MV_DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{10}
}

func (m *MV_DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_DeleteRequest.Unmarshal(m, b)
}
func (m *MV_DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *MV_DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_DeleteRequest.Merge(m, src)
}
func (m *MV_DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_MV_DeleteRequest.Size(m)
}
func (m *MV_DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_DeleteRequest proto.InternalMessageInfo

func (m *MV_DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MV_DeleteRequest) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type MV_DeleteResponse struct {
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	DelId                *pmongo.ObjectId `protobuf:"bytes,2,opt,name=delId,proto3" json:"delId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MV_DeleteResponse) Reset()         { *m = MV_DeleteResponse{} }
func (m *MV_DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*MV_DeleteResponse) ProtoMessage()    {}
func (*MV_DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{11}
}

func (m *MV_DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_DeleteResponse.Unmarshal(m, b)
}
func (m *MV_DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *MV_DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_DeleteResponse.Merge(m, src)
}
func (m *MV_DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_MV_DeleteResponse.Size(m)
}
func (m *MV_DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_DeleteResponse proto.InternalMessageInfo

func (m *MV_DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_DeleteResponse) GetDelId() *pmongo.ObjectId {
	if m != nil {
		return m.DelId
	}
	return nil
}

type MV_ReadAllRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VideoType            string   `protobuf:"bytes,3,opt,name=videoType,proto3" json:"videoType,omitempty"`
	Genre                string   `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Skip                 int64    `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_ReadAllRequest) Reset()         { *m = MV_ReadAllRequest{} }
func (m *MV_ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*MV_ReadAllRequest) ProtoMessage()    {}
func (*MV_ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{12}
}

func (m *MV_ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_ReadAllRequest.Unmarshal(m, b)
}
func (m *MV_ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *MV_ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_ReadAllRequest.Merge(m, src)
}
func (m *MV_ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_MV_ReadAllRequest.Size(m)
}
func (m *MV_ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_ReadAllRequest proto.InternalMessageInfo

func (m *MV_ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_ReadAllRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MV_ReadAllRequest) GetVideoType() string {
	if m != nil {
		return m.VideoType
	}
	return ""
}

func (m *MV_ReadAllRequest) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *MV_ReadAllRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *MV_ReadAllRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MV_ReadAllResponse struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	VideoBanks           []*VideoBank `protobuf:"bytes,2,rep,name=videoBanks,proto3" json:"videoBanks,omitempty"`
	TotalData            int32        `protobuf:"varint,3,opt,name=totalData,proto3" json:"totalData,omitempty"`
	TotalPage            int32        `protobuf:"varint,4,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MV_ReadAllResponse) Reset()         { *m = MV_ReadAllResponse{} }
func (m *MV_ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*MV_ReadAllResponse) ProtoMessage()    {}
func (*MV_ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{13}
}

func (m *MV_ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_ReadAllResponse.Unmarshal(m, b)
}
func (m *MV_ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *MV_ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_ReadAllResponse.Merge(m, src)
}
func (m *MV_ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_MV_ReadAllResponse.Size(m)
}
func (m *MV_ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_ReadAllResponse proto.InternalMessageInfo

func (m *MV_ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_ReadAllResponse) GetVideoBanks() []*VideoBank {
	if m != nil {
		return m.VideoBanks
	}
	return nil
}

func (m *MV_ReadAllResponse) GetTotalData() int32 {
	if m != nil {
		return m.TotalData
	}
	return 0
}

func (m *MV_ReadAllResponse) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

type GenreList struct {
	Id                   *pmongo.ObjectId `protobuf:"bytes,999,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Genre                []string         `protobuf:"bytes,2,rep,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *GenreList) Reset()         { *m = GenreList{} }
func (m *GenreList) String() string { return proto.CompactTextString(m) }
func (*GenreList) ProtoMessage()    {}
func (*GenreList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{14}
}

func (m *GenreList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreList.Unmarshal(m, b)
}
func (m *GenreList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreList.Marshal(b, m, deterministic)
}
func (m *GenreList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreList.Merge(m, src)
}
func (m *GenreList) XXX_Size() int {
	return xxx_messageInfo_GenreList.Size(m)
}
func (m *GenreList) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreList.DiscardUnknown(m)
}

var xxx_messageInfo_GenreList proto.InternalMessageInfo

func (m *GenreList) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GenreList) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GenreList) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

type MV_SetGenreRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_SetGenreRequest) Reset()         { *m = MV_SetGenreRequest{} }
func (m *MV_SetGenreRequest) String() string { return proto.CompactTextString(m) }
func (*MV_SetGenreRequest) ProtoMessage()    {}
func (*MV_SetGenreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{15}
}

func (m *MV_SetGenreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_SetGenreRequest.Unmarshal(m, b)
}
func (m *MV_SetGenreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_SetGenreRequest.Marshal(b, m, deterministic)
}
func (m *MV_SetGenreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_SetGenreRequest.Merge(m, src)
}
func (m *MV_SetGenreRequest) XXX_Size() int {
	return xxx_messageInfo_MV_SetGenreRequest.Size(m)
}
func (m *MV_SetGenreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_SetGenreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_SetGenreRequest proto.InternalMessageInfo

func (m *MV_SetGenreRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type MV_GetGenreResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Genre                []string `protobuf:"bytes,2,rep,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_GetGenreResponse) Reset()         { *m = MV_GetGenreResponse{} }
func (m *MV_GetGenreResponse) String() string { return proto.CompactTextString(m) }
func (*MV_GetGenreResponse) ProtoMessage()    {}
func (*MV_GetGenreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{16}
}

func (m *MV_GetGenreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_GetGenreResponse.Unmarshal(m, b)
}
func (m *MV_GetGenreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_GetGenreResponse.Marshal(b, m, deterministic)
}
func (m *MV_GetGenreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_GetGenreResponse.Merge(m, src)
}
func (m *MV_GetGenreResponse) XXX_Size() int {
	return xxx_messageInfo_MV_GetGenreResponse.Size(m)
}
func (m *MV_GetGenreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_GetGenreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_GetGenreResponse proto.InternalMessageInfo

func (m *MV_GetGenreResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_GetGenreResponse) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

type MV_RefreshRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	SourceColName        string   `protobuf:"bytes,2,opt,name=sourceColName,proto3" json:"sourceColName,omitempty"`
	TargetColName        string   `protobuf:"bytes,3,opt,name=targetColName,proto3" json:"targetColName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_RefreshRequest) Reset()         { *m = MV_RefreshRequest{} }
func (m *MV_RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*MV_RefreshRequest) ProtoMessage()    {}
func (*MV_RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{17}
}

func (m *MV_RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_RefreshRequest.Unmarshal(m, b)
}
func (m *MV_RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *MV_RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_RefreshRequest.Merge(m, src)
}
func (m *MV_RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_MV_RefreshRequest.Size(m)
}
func (m *MV_RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MV_RefreshRequest proto.InternalMessageInfo

func (m *MV_RefreshRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_RefreshRequest) GetSourceColName() string {
	if m != nil {
		return m.SourceColName
	}
	return ""
}

func (m *MV_RefreshRequest) GetTargetColName() string {
	if m != nil {
		return m.TargetColName
	}
	return ""
}

type MV_RefreshResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MV_RefreshResponse) Reset()         { *m = MV_RefreshResponse{} }
func (m *MV_RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*MV_RefreshResponse) ProtoMessage()    {}
func (*MV_RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba8f272f419d192, []int{18}
}

func (m *MV_RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MV_RefreshResponse.Unmarshal(m, b)
}
func (m *MV_RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MV_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *MV_RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MV_RefreshResponse.Merge(m, src)
}
func (m *MV_RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_MV_RefreshResponse.Size(m)
}
func (m *MV_RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MV_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MV_RefreshResponse proto.InternalMessageInfo

func (m *MV_RefreshResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MV_RefreshResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterEnum("v1.MV_ContentTypeOpt", MV_ContentTypeOpt_name, MV_ContentTypeOpt_value)
	proto.RegisterEnum("v1.MV_VideoTypeOpt", MV_VideoTypeOpt_name, MV_VideoTypeOpt_value)
	proto.RegisterEnum("v1.MV_GenreOpt", MV_GenreOpt_name, MV_GenreOpt_value)
	proto.RegisterType((*VideoBank)(nil), "v1.VideoBank")
	proto.RegisterType((*MV_PosterData)(nil), "v1.MV_PosterData")
	proto.RegisterType((*MV_CreateRequest)(nil), "v1.MV_CreateRequest")
	proto.RegisterType((*MV_CreateResponse)(nil), "v1.MV_CreateResponse")
	proto.RegisterType((*MV_CreateBulkRequest)(nil), "v1.MV_CreateBulkRequest")
	proto.RegisterType((*MV_CreateBulkResponse)(nil), "v1.MV_CreateBulkResponse")
	proto.RegisterType((*MV_ReadRequest)(nil), "v1.MV_ReadRequest")
	proto.RegisterType((*MV_ReadResponse)(nil), "v1.MV_ReadResponse")
	proto.RegisterType((*MV_UpdateRequest)(nil), "v1.MV_UpdateRequest")
	proto.RegisterType((*MV_UpdateResponse)(nil), "v1.MV_UpdateResponse")
	proto.RegisterType((*MV_DeleteRequest)(nil), "v1.MV_DeleteRequest")
	proto.RegisterType((*MV_DeleteResponse)(nil), "v1.MV_DeleteResponse")
	proto.RegisterType((*MV_ReadAllRequest)(nil), "v1.MV_ReadAllRequest")
	proto.RegisterType((*MV_ReadAllResponse)(nil), "v1.MV_ReadAllResponse")
	proto.RegisterType((*GenreList)(nil), "v1.GenreList")
	proto.RegisterType((*MV_SetGenreRequest)(nil), "v1.MV_SetGenreRequest")
	proto.RegisterType((*MV_GetGenreResponse)(nil), "v1.MV_GetGenreResponse")
	proto.RegisterType((*MV_RefreshRequest)(nil), "v1.MV_RefreshRequest")
	proto.RegisterType((*MV_RefreshResponse)(nil), "v1.MV_RefreshResponse")
}

func init() { proto.RegisterFile("video_bank_service.proto", fileDescriptor_1ba8f272f419d192) }

var fileDescriptor_1ba8f272f419d192 = []byte{
	// 1740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xdb, 0xc8,
	0x11, 0x8f, 0x24, 0x5b, 0xb6, 0x56, 0xb6, 0xbc, 0x5e, 0xcb, 0x09, 0xa3, 0xba, 0x3d, 0x1d, 0x91,
	0x16, 0x6e, 0xda, 0xd8, 0x88, 0x0f, 0x41, 0xaf, 0xed, 0x1d, 0x0e, 0x6b, 0x8a, 0xb6, 0x98, 0x90,
	0xa2, 0xba, 0xa4, 0x1c, 0xe8, 0xa1, 0x10, 0x68, 0x69, 0xa3, 0xb0, 0xa1, 0x44, 0x85, 0x5c, 0x1b,
	0xe7, 0xf7, 0x7e, 0x81, 0x3e, 0xb6, 0x0f, 0xfd, 0x50, 0xfd, 0x12, 0x05, 0xfa, 0x05, 0x0a, 0xf4,
	0xa9, 0x98, 0xe5, 0x1f, 0x51, 0xae, 0xd5, 0x22, 0xe9, 0x3d, 0x69, 0x67, 0xe6, 0x37, 0x33, 0xbf,
	0x19, 0xee, 0xee, 0xac, 0x90, 0x72, 0xeb, 0x4f, 0x78, 0x38, 0xba, 0xf6, 0xe6, 0x1f, 0x46, 0x31,
	0x8f, 0x6e, 0xfd, 0x31, 0x3f, 0x59, 0x44, 0xa1, 0x08, 0x49, 0xf9, 0xf6, 0x65, 0xeb, 0x8b, 0x69,
	0x18, 0x4e, 0x03, 0x7e, 0x2a, 0x35, 0xd7, 0x37, 0xef, 0x4e, 0x85, 0x3f, 0xe3, 0xb1, 0xf0, 0x66,
	0x8b, 0x04, 0xd4, 0x7a, 0x26, 0x7f, 0xc6, 0x2f, 0xa6, 0x7c, 0xfe, 0x62, 0x1a, 0x0a, 0x6f, 0x7a,
	0x2a, 0xbc, 0xe9, 0x94, 0x47, 0xe9, 0x4f, 0x8a, 0x3a, 0x5c, 0xcc, 0xc2, 0xf9, 0x34, 0x3c, 0x0d,
	0xaf, 0xff, 0xc0, 0xc7, 0xc2, 0x9f, 0x24, 0x6a, 0xf5, 0x9f, 0x55, 0x54, 0xbb, 0x82, 0xf4, 0xe7,
	0xde, 0xfc, 0x03, 0xf9, 0x06, 0x95, 0xfd, 0x89, 0xf2, 0xf7, 0xad, 0x76, 0xe9, 0xb8, 0x7e, 0x86,
	0x4f, 0x12, 0x97, 0x13, 0x5b, 0xba, 0x18, 0x93, 0xf3, 0xa7, 0x7f, 0xf9, 0xe3, 0x5f, 0x2b, 0xcd,
	0xeb, 0x38, 0x9c, 0xff, 0x46, 0x1d, 0xf9, 0x93, 0x5f, 0x86, 0x33, 0x5f, 0xf0, 0xd9, 0x42, 0xdc,
	0xa9, 0xac, 0xec, 0x4f, 0xc8, 0x11, 0xaa, 0x8d, 0xc3, 0xb9, 0xe0, 0x73, 0x61, 0x4c, 0x94, 0x52,
	0xbb, 0x74, 0x5c, 0x63, 0x4b, 0x05, 0xc1, 0xa8, 0xe2, 0x4f, 0xbe, 0x57, 0xca, 0x52, 0x0f, 0x4b,
	0xd2, 0x42, 0xdb, 0x8b, 0x28, 0x84, 0xe2, 0x23, 0xa5, 0x22, 0xd5, 0xb9, 0x4c, 0x9e, 0xa1, 0xdd,
	0x6c, 0xed, 0xbc, 0x0f, 0x23, 0xa1, 0x6c, 0x48, 0xc0, 0xaa, 0xb2, 0x88, 0x32, 0xbd, 0x6b, 0x1e,
	0x28, 0x9b, 0xab, 0x28, 0xa9, 0x24, 0x4d, 0xb4, 0x29, 0x7c, 0x11, 0x70, 0xa5, 0x2a, 0xad, 0x89,
	0x40, 0x08, 0xda, 0x10, 0xde, 0x34, 0x56, 0xb6, 0xdb, 0x95, 0xe3, 0x1a, 0x93, 0x6b, 0xf2, 0x12,
	0xd5, 0xe4, 0xb7, 0x70, 0xef, 0x16, 0x5c, 0xa9, 0xb5, 0x4b, 0xc7, 0x8d, 0xb3, 0x83, 0x93, 0xdb,
	0x97, 0x27, 0xd6, 0xd5, 0xe8, 0x2a, 0xd3, 0xdb, 0x0b, 0xc1, 0x96, 0x28, 0xf2, 0x53, 0xb4, 0x39,
	0xe5, 0xf3, 0x88, 0x2b, 0xa8, 0x5d, 0x39, 0x6e, 0x9c, 0xed, 0xa5, 0xf0, 0x4b, 0xd0, 0x01, 0x34,
	0xb1, 0x42, 0xb6, 0x3b, 0xee, 0x45, 0x4a, 0xbd, 0x5d, 0x3a, 0xde, 0x64, 0x72, 0x0d, 0xf5, 0x4f,
	0x6e, 0x22, 0x4f, 0xf8, 0xe1, 0x5c, 0xd9, 0x49, 0xea, 0xcf, 0x64, 0xb0, 0xc5, 0x77, 0xf3, 0x70,
	0x11, 0xfb, 0xb1, 0xd2, 0x48, 0x6c, 0x99, 0x0c, 0xb1, 0xc6, 0x5e, 0x2c, 0x94, 0xbd, 0x84, 0x39,
	0xac, 0xa1, 0xf7, 0x8b, 0xc0, 0xbb, 0xe3, 0xd1, 0x20, 0x0a, 0x14, 0x9c, 0xf4, 0x3e, 0x57, 0x90,
	0x9f, 0xa3, 0xea, 0x22, 0x8c, 0x05, 0x8f, 0x94, 0x7d, 0xf9, 0x69, 0xf7, 0x53, 0x96, 0x7d, 0xa9,
	0xec, 0x78, 0xc2, 0x63, 0x29, 0x40, 0x92, 0xf2, 0x23, 0x3e, 0x16, 0x61, 0xa4, 0x10, 0x99, 0x20,
	0x97, 0xc9, 0xaf, 0x50, 0x3d, 0xfd, 0x9e, 0xb2, 0x41, 0x07, 0xb2, 0x41, 0x87, 0x69, 0x2c, 0x6d,
	0x69, 0x81, 0xba, 0x8b, 0x48, 0xa2, 0xa2, 0x1d, 0xef, 0xd6, 0xf3, 0x03, 0xef, 0xda, 0x0f, 0x7c,
	0x71, 0xa7, 0x34, 0x25, 0xc1, 0x15, 0x5d, 0x61, 0xf7, 0xd0, 0x58, 0x39, 0x5c, 0xd9, 0x3d, 0x34,
	0x86, 0x08, 0xa9, 0x60, 0xf2, 0x5b, 0x1e, 0x28, 0x8f, 0x65, 0x1f, 0x57, 0x74, 0x40, 0xdd, 0x8f,
	0xe9, 0x58, 0xf8, 0xb7, 0x5c, 0x79, 0xd2, 0x2e, 0x1d, 0x6f, 0xb3, 0x5c, 0x26, 0x0a, 0xda, 0xf2,
	0xe3, 0x2b, 0x2f, 0xf0, 0x27, 0x8a, 0x22, 0x4d, 0x99, 0x48, 0xbe, 0x46, 0xb5, 0x71, 0xc4, 0x3d,
	0xc1, 0x27, 0x54, 0x28, 0x4f, 0x65, 0x7b, 0x5a, 0x27, 0xc9, 0x99, 0x3b, 0xc9, 0xce, 0xdc, 0x89,
	0x9b, 0x9d, 0x39, 0xb6, 0x04, 0x93, 0x6f, 0x50, 0x9d, 0x7f, 0xbf, 0xf0, 0x23, 0x3e, 0xe9, 0x78,
	0x82, 0x2b, 0x5f, 0xfe, 0x4f, 0xdf, 0x22, 0x5c, 0xfd, 0x35, 0xda, 0x5d, 0xf9, 0x02, 0x64, 0x07,
	0x95, 0xe2, 0xf4, 0xd8, 0x94, 0x62, 0x90, 0x66, 0xe9, 0x61, 0x29, 0xcd, 0x40, 0x0a, 0xd2, 0x33,
	0x52, 0x0a, 0xd4, 0xdf, 0x21, 0x0c, 0x0d, 0x97, 0x44, 0x18, 0xff, 0x78, 0xc3, 0x63, 0x01, 0xc7,
	0xcb, 0x5b, 0xf8, 0xa9, 0x3f, 0x2c, 0xc9, 0x2f, 0xd2, 0xcd, 0x0c, 0x27, 0x5b, 0x46, 0xaa, 0x9f,
	0xed, 0xc2, 0xb7, 0xca, 0x8f, 0x3b, 0x5b, 0xda, 0xd5, 0x6b, 0xb4, 0x5f, 0x08, 0x19, 0x2f, 0xc2,
	0x79, 0xcc, 0x1f, 0x88, 0xf9, 0x5b, 0x79, 0x41, 0x94, 0x3f, 0xeb, 0x7e, 0x50, 0x7f, 0x8f, 0x9a,
	0x79, 0x8e, 0xf3, 0x9b, 0xe0, 0xc3, 0x7a, 0xea, 0x5f, 0xa1, 0xdd, 0x9c, 0x9a, 0xe9, 0xc7, 0x42,
	0x29, 0xb7, 0x2b, 0xff, 0x49, 0x7f, 0x15, 0xa3, 0xbe, 0x47, 0x87, 0xf7, 0xc2, 0xaf, 0x2d, 0xe3,
	0x5b, 0xb8, 0x8b, 0xe2, 0x34, 0xea, 0x27, 0xd5, 0x01, 0x7e, 0x6a, 0x07, 0x35, 0xac, 0xab, 0x11,
	0xe3, 0xde, 0x64, 0x7d, 0x09, 0x8d, 0xbc, 0x53, 0x35, 0x79, 0x39, 0xa6, 0xd7, 0x5f, 0x25, 0xbf,
	0xfe, 0xd4, 0x3e, 0xda, 0xcb, 0xa3, 0xac, 0x65, 0xfa, 0x49, 0x1f, 0xd1, 0x93, 0xfb, 0x62, 0xb0,
	0x98, 0xfc, 0x60, 0xfb, 0x22, 0x2d, 0xa3, 0x92, 0x95, 0xa1, 0xbe, 0x93, 0xfb, 0x24, 0x4b, 0xb1,
	0x96, 0xf6, 0x77, 0x68, 0xe3, 0x66, 0x61, 0x7c, 0xd6, 0x4e, 0x91, 0x8e, 0x2a, 0x93, 0xa5, 0x74,
	0x78, 0xc0, 0xff, 0x5b, 0x29, 0xf7, 0x9b, 0x7c, 0x84, 0x6a, 0x37, 0x92, 0xda, 0xe4, 0xfc, 0x2e,
	0x25, 0xbd, 0x54, 0xa8, 0xef, 0x25, 0xf7, 0x2c, 0xe6, 0x5a, 0xee, 0x14, 0x6d, 0x4e, 0x78, 0xf0,
	0x79, 0xe4, 0x13, 0x4f, 0xf5, 0xcf, 0x25, 0x99, 0x0a, 0xbe, 0x2d, 0x0d, 0x82, 0xf5, 0xfc, 0xf3,
	0xc9, 0x54, 0x2e, 0x4e, 0xa6, 0xa3, 0xe2, 0x14, 0x4a, 0xab, 0x58, 0x0e, 0x9c, 0x66, 0x36, 0x70,
	0x92, 0x89, 0xb8, 0x9c, 0x2f, 0xf1, 0x07, 0x7f, 0x21, 0x07, 0x60, 0x85, 0xc9, 0x35, 0x20, 0x03,
	0x7f, 0xe6, 0x0b, 0x39, 0xf7, 0x2a, 0x2c, 0x11, 0xd4, 0x3f, 0x95, 0x10, 0x29, 0x72, 0x5b, 0xdb,
	0x87, 0x17, 0x08, 0xe5, 0xfb, 0x20, 0x7e, 0xf8, 0x04, 0x16, 0x00, 0xc0, 0x5a, 0x84, 0xc2, 0x0b,
	0xe0, 0x2e, 0x93, 0xac, 0x37, 0xd9, 0x52, 0x91, 0x5b, 0xfb, 0xde, 0x34, 0x61, 0x9e, 0x59, 0x41,
	0xa1, 0x7e, 0x44, 0x35, 0x39, 0x30, 0xe1, 0x1c, 0xff, 0x9f, 0x8f, 0x90, 0x07, 0x9b, 0x9c, 0x34,
	0xac, 0x2c, 0xc7, 0x59, 0x22, 0xa8, 0x3f, 0x93, 0x5d, 0x70, 0xb8, 0x90, 0x89, 0xd7, 0x7e, 0x22,
	0xf5, 0x5b, 0x74, 0x20, 0xc7, 0x79, 0x86, 0x5b, 0xdb, 0xae, 0x87, 0xd3, 0x7c, 0x4c, 0x37, 0xc2,
	0xbb, 0x88, 0xc7, 0xef, 0xd7, 0x6f, 0x84, 0x67, 0x68, 0x37, 0x0e, 0x6f, 0xa2, 0x31, 0xd7, 0xc2,
	0xa0, 0xe7, 0xcd, 0xb2, 0x0d, 0xb1, 0xaa, 0x04, 0x94, 0xf0, 0xa2, 0x29, 0x17, 0x19, 0x2a, 0xd9,
	0x1c, 0xab, 0x4a, 0xb5, 0x93, 0x7e, 0xdf, 0x34, 0xe5, 0x5a, 0xc2, 0x47, 0xa8, 0xe6, 0xc7, 0xce,
	0xcd, 0x78, 0xcc, 0xe3, 0x58, 0xe6, 0xdb, 0x66, 0x4b, 0xc5, 0xf3, 0xe7, 0xc9, 0x40, 0x58, 0x19,
	0xea, 0x64, 0x1b, 0x6d, 0x5c, 0x30, 0x5d, 0xc7, 0x8f, 0x48, 0x1d, 0x6d, 0xf5, 0x99, 0x6e, 0x19,
	0x03, 0x0b, 0x97, 0x9e, 0xff, 0xad, 0x2c, 0xaf, 0xb2, 0xe2, 0x13, 0x89, 0x20, 0x54, 0xbd, 0xd4,
	0x7b, 0x23, 0xeb, 0x0a, 0x3f, 0x22, 0x3b, 0x68, 0xdb, 0x1a, 0x38, 0x86, 0x06, 0x52, 0x09, 0x24,
	0xda, 0x33, 0x2c, 0x1d, 0xa4, 0x32, 0x69, 0x20, 0xa4, 0xf7, 0x2e, 0x4d, 0xc3, 0xe9, 0x82, 0x5c,
	0x21, 0xbb, 0xa8, 0x76, 0xa9, 0x33, 0x8b, 0x4a, 0xd7, 0x0d, 0x00, 0x77, 0x06, 0xae, 0x26, 0x8d,
	0x9b, 0x60, 0xbc, 0x60, 0x7a, 0x2f, 0x11, 0xab, 0xe0, 0xdb, 0x1f, 0xf4, 0x5e, 0xd3, 0x73, 0x03,
	0xe4, 0x2d, 0x00, 0xbb, 0xf4, 0xb5, 0xf1, 0x06, 0xa4, 0x6d, 0xb2, 0x8f, 0x76, 0x8d, 0x5e, 0xc7,
	0xee, 0xe9, 0x8e, 0x91, 0x44, 0xab, 0x01, 0xa0, 0x6b, 0xf4, 0x3a, 0x12, 0x5e, 0x07, 0x77, 0x97,
	0x5e, 0x52, 0xd3, 0xbe, 0x04, 0x79, 0x07, 0xa2, 0x77, 0xf5, 0x73, 0xa6, 0xbf, 0x05, 0x71, 0x17,
	0x4a, 0x74, 0xbb, 0x54, 0x62, 0x1b, 0x64, 0x0f, 0xd5, 0x2f, 0x07, 0xaf, 0x29, 0xa3, 0xae, 0x54,
	0xec, 0x81, 0xe2, 0x35, 0xed, 0xd3, 0x9e, 0xee, 0xc8, 0x42, 0x30, 0x78, 0xbf, 0xb1, 0x99, 0x9e,
	0xa4, 0xda, 0x87, 0xe0, 0x5a, 0xd7, 0xc8, 0xcc, 0x04, 0x64, 0xcb, 0x66, 0xb6, 0xa6, 0xd9, 0x20,
	0x1f, 0x80, 0xec, 0xf4, 0x69, 0x2f, 0xad, 0xbb, 0x09, 0xf1, 0xa8, 0xe3, 0x50, 0x2b, 0x75, 0x38,
	0x7c, 0xfe, 0xaf, 0x0a, 0xaa, 0x17, 0x1e, 0x92, 0xd0, 0x50, 0xaa, 0xb9, 0x86, 0xdd, 0xc3, 0x8f,
	0x60, 0xad, 0xd9, 0x96, 0xde, 0x19, 0xe2, 0x12, 0xd0, 0x64, 0xb6, 0x45, 0x7b, 0x9a, 0x8e, 0xcb,
	0xb2, 0x03, 0x5d, 0x66, 0x98, 0xa6, 0xce, 0x70, 0x05, 0x60, 0x5d, 0x9b, 0x31, 0x9b, 0xe1, 0x0d,
	0x80, 0x75, 0x0d, 0xc7, 0xb5, 0xd9, 0x10, 0x6f, 0x82, 0x21, 0xe1, 0x8a, 0xab, 0xa4, 0x86, 0x36,
	0x3b, 0x8c, 0x5a, 0x14, 0x6f, 0x01, 0xe6, 0x82, 0xf6, 0x5c, 0xea, 0x0c, 0xf1, 0x36, 0x60, 0x1c,
	0xcd, 0x18, 0x5d, 0x18, 0xb8, 0x06, 0x18, 0xf9, 0xc9, 0x30, 0x82, 0xa5, 0xc6, 0x60, 0x59, 0x27,
	0x04, 0x35, 0x12, 0xc4, 0x28, 0xf3, 0xda, 0x21, 0x4d, 0x84, 0x13, 0x96, 0x23, 0xda, 0xb9, 0xd2,
	0x7b, 0xee, 0x80, 0xe9, 0x49, 0x2b, 0x2f, 0x8c, 0x84, 0x7c, 0x03, 0x1a, 0xe5, 0xf4, 0x0d, 0x66,
	0xb8, 0x03, 0x6a, 0xe2, 0x3d, 0xa0, 0xcc, 0x74, 0xd3, 0xb8, 0x04, 0x23, 0x86, 0xac, 0x2e, 0xa3,
	0x57, 0xba, 0x89, 0xf7, 0x21, 0x95, 0xe3, 0x0e, 0x4d, 0x1d, 0x13, 0x08, 0xa0, 0x99, 0xd4, 0x71,
	0x0c, 0x0d, 0x1f, 0x40, 0xab, 0xde, 0x18, 0x1d, 0x67, 0x74, 0x41, 0x2d, 0xc3, 0x1c, 0xe2, 0x26,
	0x58, 0xad, 0xa1, 0xe3, 0xea, 0x6c, 0x88, 0x0f, 0xa5, 0x00, 0x9b, 0x8d, 0x9a, 0xf8, 0xb1, 0xcc,
	0x35, 0xe8, 0xeb, 0xac, 0xab, 0x33, 0x1b, 0x3f, 0x81, 0x5c, 0x7d, 0xdb, 0x34, 0x5c, 0x43, 0x73,
	0xb0, 0x42, 0x30, 0xda, 0xb1, 0x28, 0x73, 0x0d, 0x6a, 0x8e, 0x28, 0x73, 0x1d, 0xfc, 0x54, 0xd6,
	0xdc, 0xb7, 0x61, 0xdd, 0x82, 0xbd, 0x0e, 0x59, 0xf0, 0x8f, 0xc8, 0x63, 0x44, 0x64, 0x87, 0x5d,
	0x43, 0x1b, 0x65, 0xdd, 0x75, 0xf0, 0x11, 0xd9, 0x42, 0x95, 0xb7, 0x94, 0xe1, 0x1f, 0x83, 0x5b,
	0xca, 0xe5, 0x27, 0x72, 0x13, 0xd9, 0xa6, 0x39, 0x7c, 0x6b, 0xdb, 0x1d, 0xfc, 0x05, 0x51, 0x50,
	0x53, 0x63, 0x90, 0x90, 0x9a, 0xe6, 0x70, 0x44, 0x35, 0xcd, 0xa4, 0x86, 0xa5, 0x77, 0x70, 0x1b,
	0xaa, 0xe8, 0xd8, 0xda, 0xc0, 0xd2, 0x7b, 0x2e, 0x65, 0x43, 0xfc, 0x25, 0x44, 0xb1, 0xdd, 0x2e,
	0x84, 0x1e, 0x9f, 0xfd, 0xa3, 0x82, 0x70, 0x7e, 0xcd, 0x3a, 0xc9, 0x7f, 0x42, 0xf2, 0x0a, 0x55,
	0x93, 0xd7, 0x0d, 0x69, 0x66, 0x6f, 0xee, 0xe2, 0x13, 0xb0, 0x75, 0x78, 0x4f, 0x9b, 0x9e, 0x7c,
	0x8a, 0xd0, 0xf2, 0x51, 0x44, 0x94, 0x15, 0x50, 0xe1, 0x19, 0xd6, 0x7a, 0xfa, 0x80, 0x25, 0x0d,
	0x71, 0x8a, 0x36, 0x60, 0x5e, 0x10, 0x92, 0x42, 0x0a, 0x4f, 0x9f, 0xd6, 0xc1, 0x8a, 0x2e, 0x75,
	0x78, 0x85, 0xaa, 0xc9, 0x1b, 0x21, 0xa7, 0xba, 0xf2, 0x2a, 0xc9, 0xa9, 0xde, 0x7b, 0x48, 0xbc,
	0x42, 0xd5, 0x64, 0x3c, 0xe7, 0x6e, 0x2b, 0x2f, 0x80, 0xdc, 0xed, 0xde, 0x0c, 0xff, 0x1a, 0x6d,
	0xa5, 0xe3, 0x8c, 0x1c, 0x16, 0xd8, 0x2c, 0x47, 0x6f, 0xeb, 0xf1, 0x7d, 0x75, 0xea, 0xf9, 0x1d,
	0xda, 0xc9, 0xae, 0x76, 0x39, 0x7b, 0x32, 0xdc, 0xbd, 0xb9, 0xd0, 0x7a, 0x92, 0xff, 0xad, 0xbb,
	0x37, 0x07, 0xce, 0xd1, 0x7e, 0x7a, 0xd3, 0x6a, 0x61, 0x10, 0xc0, 0x3f, 0xeb, 0x70, 0x5e, 0x20,
	0x51, 0xbc, 0xf6, 0x0b, 0x24, 0x56, 0xae, 0xe6, 0xeb, 0xaa, 0xfc, 0xab, 0xf0, 0xd5, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0x8a, 0xb1, 0x1b, 0x08, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoBankServiceClient is the client API for VideoBankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoBankServiceClient interface {
	Create(ctx context.Context, in *MV_CreateRequest, opts ...grpc.CallOption) (*MV_CreateResponse, error)
	CreateBulk(ctx context.Context, in *MV_CreateBulkRequest, opts ...grpc.CallOption) (*MV_CreateBulkResponse, error)
	Read(ctx context.Context, in *MV_ReadRequest, opts ...grpc.CallOption) (*MV_ReadResponse, error)
	Update(ctx context.Context, in *MV_UpdateRequest, opts ...grpc.CallOption) (*MV_UpdateResponse, error)
	Delete(ctx context.Context, in *MV_DeleteRequest, opts ...grpc.CallOption) (*MV_DeleteResponse, error)
	ReadAll(ctx context.Context, in *MV_ReadAllRequest, opts ...grpc.CallOption) (*MV_ReadAllResponse, error)
	GetGenreList(ctx context.Context, in *MV_SetGenreRequest, opts ...grpc.CallOption) (*MV_GetGenreResponse, error)
	RefreshCollection(ctx context.Context, in *MV_RefreshRequest, opts ...grpc.CallOption) (*MV_RefreshResponse, error)
}

type videoBankServiceClient struct {
	cc *grpc.ClientConn
}

func NewVideoBankServiceClient(cc *grpc.ClientConn) VideoBankServiceClient {
	return &videoBankServiceClient{cc}
}

func (c *videoBankServiceClient) Create(ctx context.Context, in *MV_CreateRequest, opts ...grpc.CallOption) (*MV_CreateResponse, error) {
	out := new(MV_CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) CreateBulk(ctx context.Context, in *MV_CreateBulkRequest, opts ...grpc.CallOption) (*MV_CreateBulkResponse, error) {
	out := new(MV_CreateBulkResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/CreateBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) Read(ctx context.Context, in *MV_ReadRequest, opts ...grpc.CallOption) (*MV_ReadResponse, error) {
	out := new(MV_ReadResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) Update(ctx context.Context, in *MV_UpdateRequest, opts ...grpc.CallOption) (*MV_UpdateResponse, error) {
	out := new(MV_UpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) Delete(ctx context.Context, in *MV_DeleteRequest, opts ...grpc.CallOption) (*MV_DeleteResponse, error) {
	out := new(MV_DeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) ReadAll(ctx context.Context, in *MV_ReadAllRequest, opts ...grpc.CallOption) (*MV_ReadAllResponse, error) {
	out := new(MV_ReadAllResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) GetGenreList(ctx context.Context, in *MV_SetGenreRequest, opts ...grpc.CallOption) (*MV_GetGenreResponse, error) {
	out := new(MV_GetGenreResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/GetGenreList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoBankServiceClient) RefreshCollection(ctx context.Context, in *MV_RefreshRequest, opts ...grpc.CallOption) (*MV_RefreshResponse, error) {
	out := new(MV_RefreshResponse)
	err := c.cc.Invoke(ctx, "/v1.VideoBankService/RefreshCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoBankServiceServer is the server API for VideoBankService service.
type VideoBankServiceServer interface {
	Create(context.Context, *MV_CreateRequest) (*MV_CreateResponse, error)
	CreateBulk(context.Context, *MV_CreateBulkRequest) (*MV_CreateBulkResponse, error)
	Read(context.Context, *MV_ReadRequest) (*MV_ReadResponse, error)
	Update(context.Context, *MV_UpdateRequest) (*MV_UpdateResponse, error)
	Delete(context.Context, *MV_DeleteRequest) (*MV_DeleteResponse, error)
	ReadAll(context.Context, *MV_ReadAllRequest) (*MV_ReadAllResponse, error)
	GetGenreList(context.Context, *MV_SetGenreRequest) (*MV_GetGenreResponse, error)
	RefreshCollection(context.Context, *MV_RefreshRequest) (*MV_RefreshResponse, error)
}

func RegisterVideoBankServiceServer(s *grpc.Server, srv VideoBankServiceServer) {
	s.RegisterService(&_VideoBankService_serviceDesc, srv)
}

func _VideoBankService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).Create(ctx, req.(*MV_CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_CreateBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_CreateBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).CreateBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/CreateBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).CreateBulk(ctx, req.(*MV_CreateBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).Read(ctx, req.(*MV_ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).Update(ctx, req.(*MV_UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).Delete(ctx, req.(*MV_DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).ReadAll(ctx, req.(*MV_ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_GetGenreList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_SetGenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).GetGenreList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/GetGenreList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).GetGenreList(ctx, req.(*MV_SetGenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoBankService_RefreshCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MV_RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoBankServiceServer).RefreshCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VideoBankService/RefreshCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoBankServiceServer).RefreshCollection(ctx, req.(*MV_RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoBankService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VideoBankService",
	HandlerType: (*VideoBankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VideoBankService_Create_Handler,
		},
		{
			MethodName: "CreateBulk",
			Handler:    _VideoBankService_CreateBulk_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _VideoBankService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VideoBankService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VideoBankService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _VideoBankService_ReadAll_Handler,
		},
		{
			MethodName: "GetGenreList",
			Handler:    _VideoBankService_GetGenreList_Handler,
		},
		{
			MethodName: "RefreshCollection",
			Handler:    _VideoBankService_RefreshCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video_bank_service.proto",
}
